---
# file: site.yml
# this playbook bootstrap a dummy module
# with the above informations
# then your are ready to finish the module ;-)
- hosts: home-sweet-home

  roles:
  - dummy

  vars:
    # to directory tree and class/module/name purpose
    module_name: joplin # will become th_johndoe
    class_name: Joplin # will become ServiceJohndoe

    # for setup.py purpose
    author: foxmask
    author_email: foxmask protonmail
    description: Joplin Editor
    details: Joplin Markdown Editor
    url: https://github.com/push-things/django-th-joplin   # change it to the repository of your own
    download_url: https://github.com/push-things/django-th-joplin/archive/trigger-happy-joplin-

    # for dependencies purpose
    external_api: joplin_api
    external_api_class: JoplinApi
    external_api_version: 1.2.2

    # for oauth if any
    oauth_version: ''   # oauth1 or oauth2 or leave empty if this module does not handle Oauth process at all
    # URL to access to the OAuth of the service
    AUTH_URL: ''
    ACC_TOKEN: ''
    REQ_TOKEN: ''
