---
# file roles/dummy/tasks/main.yml


- debug: msg="Starting the creation of the 'Trigger Happy' module '{{ module_name }}' ..."

- name: create folder of the module name
  command: mkdir -p th_{{ module_name }}/templates/{{ module_name }}

- name: copy of th_dummy/__init__.py
  template: src=django-th-dummy/th_dummy/__init__.py dest=th_{{ module_name }}/__init__.py

- name: copy of th_dummy/tests.py
  template: src=django-th-dummy/th_dummy/tests.py dest=th_{{ module_name }}/tests.py

- name: copy of my_dummy.py to my_{{ module_name }}.py
  template: src=django-th-dummy/th_dummy/my_dummy.py dest=th_{{ module_name }}/my_{{ module_name }}.py

- name: copy of models.py
  template: src=django-th-dummy/th_dummy/models.py dest=th_{{ module_name }}/models.py

- name: copy of forms.py
  template: src=django-th-dummy/th_dummy/forms.py dest=th_{{ module_name }}/forms.py

- name: copy of tests.py
  template: src=django-th-dummy/th_dummy/tests.py dest=th_{{ module_name }}/tests.py

- name: copy of the templates
  copy: src=roles/dummy/templates/django-th-dummy/th_dummy/templates/th_dummy/ dest=th_{{ module_name }}/templates/{{ module_name }}/

- name: remove unecessary callback.html template
  file: path=th_{{ module_name }}/templates/{{ module_name }}/callback.html state=absent
  when: oauth_version == ''


- debug: msg="Your new 'Trigger Happy' module '{{ module_name }}' is now ready !"

